import Head from 'next/head'
import Container from '../components/container';
import Layout from "../components/layout";
import Navbar from '../components/navbar';

export default function About() {
  return (
    <>
      <Layout>
        <Head>
          <title>Turnê MultiShop Brasil</title>
          <meta name="description" content="Turnê MultiShop Brasil" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar />
        <br /><br /><br /><br /><br /><br />
        <Container>

          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat sem nibh. Curabitur sed lorem efficitur, imperdiet metus vel, euismod mauris. Sed scelerisque nisl quis vestibulum rhoncus. Mauris diam ante, lobortis id pharetra non, congue ut felis. Nullam auctor ultrices elit sed feugiat. Nulla et tempus mi, vel tempus neque. Aenean a tincidunt nisi.</p>
          <p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin enim augue, vehicula et bibendum ac, interdum a velit. Sed ac enim quis justo volutpat consequat. Praesent aliquam libero in varius lobortis. Suspendisse fermentum metus sed molestie vehicula. Donec porttitor tellus id lorem tincidunt condimentum. Donec consectetur justo vel massa malesuada, a convallis est sodales. Quisque quis purus iaculis, gravida orci sit amet, faucibus erat. Morbi vestibulum tempor diam eget vulputate.</p>
          <p>Sed pulvinar nunc ligula. Donec maximus urna ultricies, laoreet mi sed, facilisis sem. Ut suscipit quis ipsum eget ornare. Nam sapien nisl, placerat nec nunc et, mollis auctor quam. Cras pulvinar, ligula at bibendum lobortis, arcu erat cursus nisi, sed luctus magna libero a leo. Nullam tristique diam molestie mauris bibendum, id ornare dolor interdum. Maecenas faucibus, tortor dapibus sollicitudin dignissim, risus est aliquam augue, quis tincidunt sem elit in nisl. Morbi tempor ligula vel consequat dapibus. Sed nulla nibh, cursus sed mi et, porttitor ullamcorper nulla. Vivamus rhoncus placerat nisl eget posuere. Donec varius vitae justo sed condimentum. Quisque tortor diam, sollicitudin ac neque sit amet, tincidunt condimentum ligula. Vivamus tempus lectus sit amet mauris tempor, eget dignissim ex scelerisque.</p>
          <p>Donec malesuada scelerisque mi, tincidunt laoreet est aliquet non. Maecenas nec egestas lectus, et fermentum elit. Etiam bibendum tellus lorem, ac tempor nibh porttitor vitae. Ut commodo purus in lectus placerat, id viverra ligula sollicitudin. Curabitur ultricies libero id diam sollicitudin, vel commodo lectus pharetra. Nullam lobortis luctus convallis. Nam id tellus efficitur, vehicula lacus quis, pellentesque elit.</p>
          <p>Sed consequat tempus nibh et venenatis. Duis rutrum aliquam mi, ac sollicitudin risus ultricies quis. Integer faucibus dignissim nisl sed porttitor. Sed venenatis fermentum quam. Etiam porttitor ligula nec nisi accumsan dignissim. Sed vehicula diam eu elit euismod, ut pellentesque dolor hendrerit. Cras eget tempor tortor, vel pharetra mi. Nam in leo quis augue faucibus ullamcorper ac eget turpis. Ut finibus mollis nibh, eget eleifend felis rutrum a. Proin elementum feugiat elementum. Suspendisse potenti. Vivamus in dolor laoreet, imperdiet lacus sit amet, mollis lacus. Praesent a elit ac leo ultrices congue.</p>


          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat sem nibh. Curabitur sed lorem efficitur, imperdiet metus vel, euismod mauris. Sed scelerisque nisl quis vestibulum rhoncus. Mauris diam ante, lobortis id pharetra non, congue ut felis. Nullam auctor ultrices elit sed feugiat. Nulla et tempus mi, vel tempus neque. Aenean a tincidunt nisi.</p>
          <p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin enim augue, vehicula et bibendum ac, interdum a velit. Sed ac enim quis justo volutpat consequat. Praesent aliquam libero in varius lobortis. Suspendisse fermentum metus sed molestie vehicula. Donec porttitor tellus id lorem tincidunt condimentum. Donec consectetur justo vel massa malesuada, a convallis est sodales. Quisque quis purus iaculis, gravida orci sit amet, faucibus erat. Morbi vestibulum tempor diam eget vulputate.</p>
          <p>Sed pulvinar nunc ligula. Donec maximus urna ultricies, laoreet mi sed, facilisis sem. Ut suscipit quis ipsum eget ornare. Nam sapien nisl, placerat nec nunc et, mollis auctor quam. Cras pulvinar, ligula at bibendum lobortis, arcu erat cursus nisi, sed luctus magna libero a leo. Nullam tristique diam molestie mauris bibendum, id ornare dolor interdum. Maecenas faucibus, tortor dapibus sollicitudin dignissim, risus est aliquam augue, quis tincidunt sem elit in nisl. Morbi tempor ligula vel consequat dapibus. Sed nulla nibh, cursus sed mi et, porttitor ullamcorper nulla. Vivamus rhoncus placerat nisl eget posuere. Donec varius vitae justo sed condimentum. Quisque tortor diam, sollicitudin ac neque sit amet, tincidunt condimentum ligula. Vivamus tempus lectus sit amet mauris tempor, eget dignissim ex scelerisque.</p>
          <p>Donec malesuada scelerisque mi, tincidunt laoreet est aliquet non. Maecenas nec egestas lectus, et fermentum elit. Etiam bibendum tellus lorem, ac tempor nibh porttitor vitae. Ut commodo purus in lectus placerat, id viverra ligula sollicitudin. Curabitur ultricies libero id diam sollicitudin, vel commodo lectus pharetra. Nullam lobortis luctus convallis. Nam id tellus efficitur, vehicula lacus quis, pellentesque elit.</p>
          <p>Sed consequat tempus nibh et venenatis. Duis rutrum aliquam mi, ac sollicitudin risus ultricies quis. Integer faucibus dignissim nisl sed porttitor. Sed venenatis fermentum quam. Etiam porttitor ligula nec nisi accumsan dignissim. Sed vehicula diam eu elit euismod, ut pellentesque dolor hendrerit. Cras eget tempor tortor, vel pharetra mi. Nam in leo quis augue faucibus ullamcorper ac eget turpis. Ut finibus mollis nibh, eget eleifend felis rutrum a. Proin elementum feugiat elementum. Suspendisse potenti. Vivamus in dolor laoreet, imperdiet lacus sit amet, mollis lacus. Praesent a elit ac leo ultrices congue.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat sem nibh. Curabitur sed lorem efficitur, imperdiet metus vel, euismod mauris. Sed scelerisque nisl quis vestibulum rhoncus. Mauris diam ante, lobortis id pharetra non, congue ut felis. Nullam auctor ultrices elit sed feugiat. Nulla et tempus mi, vel tempus neque. Aenean a tincidunt nisi.</p>
          <p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin enim augue, vehicula et bibendum ac, interdum a velit. Sed ac enim quis justo volutpat consequat. Praesent aliquam libero in varius lobortis. Suspendisse fermentum metus sed molestie vehicula. Donec porttitor tellus id lorem tincidunt condimentum. Donec consectetur justo vel massa malesuada, a convallis est sodales. Quisque quis purus iaculis, gravida orci sit amet, faucibus erat. Morbi vestibulum tempor diam eget vulputate.</p>
          <p>Sed pulvinar nunc ligula. Donec maximus urna ultricies, laoreet mi sed, facilisis sem. Ut suscipit quis ipsum eget ornare. Nam sapien nisl, placerat nec nunc et, mollis auctor quam. Cras pulvinar, ligula at bibendum lobortis, arcu erat cursus nisi, sed luctus magna libero a leo. Nullam tristique diam molestie mauris bibendum, id ornare dolor interdum. Maecenas faucibus, tortor dapibus sollicitudin dignissim, risus est aliquam augue, quis tincidunt sem elit in nisl. Morbi tempor ligula vel consequat dapibus. Sed nulla nibh, cursus sed mi et, porttitor ullamcorper nulla. Vivamus rhoncus placerat nisl eget posuere. Donec varius vitae justo sed condimentum. Quisque tortor diam, sollicitudin ac neque sit amet, tincidunt condimentum ligula. Vivamus tempus lectus sit amet mauris tempor, eget dignissim ex scelerisque.</p>
          <p>Donec malesuada scelerisque mi, tincidunt laoreet est aliquet non. Maecenas nec egestas lectus, et fermentum elit. Etiam bibendum tellus lorem, ac tempor nibh porttitor vitae. Ut commodo purus in lectus placerat, id viverra ligula sollicitudin. Curabitur ultricies libero id diam sollicitudin, vel commodo lectus pharetra. Nullam lobortis luctus convallis. Nam id tellus efficitur, vehicula lacus quis, pellentesque elit.</p>
          <p>Sed consequat tempus nibh et venenatis. Duis rutrum aliquam mi, ac sollicitudin risus ultricies quis. Integer faucibus dignissim nisl sed porttitor. Sed venenatis fermentum quam. Etiam porttitor ligula nec nisi accumsan dignissim. Sed vehicula diam eu elit euismod, ut pellentesque dolor hendrerit. Cras eget tempor tortor, vel pharetra mi. Nam in leo quis augue faucibus ullamcorper ac eget turpis. Ut finibus mollis nibh, eget eleifend felis rutrum a. Proin elementum feugiat elementum. Suspendisse potenti. Vivamus in dolor laoreet, imperdiet lacus sit amet, mollis lacus. Praesent a elit ac leo ultrices congue.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec volutpat sem nibh. Curabitur sed lorem efficitur, imperdiet metus vel, euismod mauris. Sed scelerisque nisl quis vestibulum rhoncus. Mauris diam ante, lobortis id pharetra non, congue ut felis. Nullam auctor ultrices elit sed feugiat. Nulla et tempus mi, vel tempus neque. Aenean a tincidunt nisi.</p>
          <p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin enim augue, vehicula et bibendum ac, interdum a velit. Sed ac enim quis justo volutpat consequat. Praesent aliquam libero in varius lobortis. Suspendisse fermentum metus sed molestie vehicula. Donec porttitor tellus id lorem tincidunt condimentum. Donec consectetur justo vel massa malesuada, a convallis est sodales. Quisque quis purus iaculis, gravida orci sit amet, faucibus erat. Morbi vestibulum tempor diam eget vulputate.</p>
          <p>Sed pulvinar nunc ligula. Donec maximus urna ultricies, laoreet mi sed, facilisis sem. Ut suscipit quis ipsum eget ornare. Nam sapien nisl, placerat nec nunc et, mollis auctor quam. Cras pulvinar, ligula at bibendum lobortis, arcu erat cursus nisi, sed luctus magna libero a leo. Nullam tristique diam molestie mauris bibendum, id ornare dolor interdum. Maecenas faucibus, tortor dapibus sollicitudin dignissim, risus est aliquam augue, quis tincidunt sem elit in nisl. Morbi tempor ligula vel consequat dapibus. Sed nulla nibh, cursus sed mi et, porttitor ullamcorper nulla. Vivamus rhoncus placerat nisl eget posuere. Donec varius vitae justo sed condimentum. Quisque tortor diam, sollicitudin ac neque sit amet, tincidunt condimentum ligula. Vivamus tempus lectus sit amet mauris tempor, eget dignissim ex scelerisque.</p>
          <p>Donec malesuada scelerisque mi, tincidunt laoreet est aliquet non. Maecenas nec egestas lectus, et fermentum elit. Etiam bibendum tellus lorem, ac tempor nibh porttitor vitae. Ut commodo purus in lectus placerat, id viverra ligula sollicitudin. Curabitur ultricies libero id diam sollicitudin, vel commodo lectus pharetra. Nullam lobortis luctus convallis. Nam id tellus efficitur, vehicula lacus quis, pellentesque elit.</p>
          <p>Sed consequat tempus nibh et venenatis. Duis rutrum aliquam mi, ac sollicitudin risus ultricies quis. Integer faucibus dignissim nisl sed porttitor. Sed venenatis fermentum quam. Etiam porttitor ligula nec nisi accumsan dignissim. Sed vehicula diam eu elit euismod, ut pellentesque dolor hendrerit. Cras eget tempor tortor, vel pharetra mi. Nam in leo quis augue faucibus ullamcorper ac eget turpis. Ut finibus mollis nibh, eget eleifend felis rutrum a. Proin elementum feugiat elementum. Suspendisse potenti. Vivamus in dolor laoreet, imperdiet lacus sit amet, mollis lacus. Praesent a elit ac leo ultrices congue.</p>


        </Container>

      </Layout>
    </>
  )
}